on: push
name: Test and Lint
jobs:
  test-and-list:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - run: composer update --no-scripts
    - run: cp .env.ci .env.testing
    - run: |
        npm install
        npm run dev

    - run: php artisan test

    - run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - run: php phpcs.phar
